/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import com.formdev.flatlaf.FlatLaf;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author huynh
 */
public class FormTTChuyen extends javax.swing.JPanel {
    /**
     * Creates new form FormTTChuyen
     */
    public FormTTChuyen() {
        initComponents();
        init();
        UIManager.addPropertyChangeListener(evt -> {
            if ("lookAndFeel".equals(evt.getPropertyName())) {
                updatePanelColors();
            }
        });
    }
    private void init() {
        setLayout(new MigLayout("al center center"));
        
        ImageIcon iconLabel3 = new ImageIcon(getClass().getResource("/raven/icon/png/xe.png"));
        Image scaledIcon3 = iconLabel3.getImage().getScaledInstance(110, 130, Image.SCALE_SMOOTH);
        jLabel3.setIcon(new ImageIcon(scaledIcon3));
        jLabel3.setIconTextGap(5);
        jLabel3.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabel3.setVerticalTextPosition(SwingConstants.CENTER);
        
        ImageIcon iconLabel1 = new ImageIcon(getClass().getResource("/raven/icon/png/begin.png"));
        Image scaledIcon1 = iconLabel1.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(scaledIcon1));
        jLabel1.setIconTextGap(5);
        jLabel1.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabel1.setVerticalTextPosition(SwingConstants.CENTER);

        ImageIcon iconLabel2 = new ImageIcon(getClass().getResource("/raven/icon/png/end.png"));
        Image scaledIcon2 = iconLabel2.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        jLabel2.setIcon(new ImageIcon(scaledIcon2));
        jLabel2.setIconTextGap(5);
        jLabel2.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabel2.setVerticalTextPosition(SwingConstants.CENTER);
        
        ImageIcon iconLabel4 = new ImageIcon(getClass().getResource("/raven/icon/png/downarrow.png"));
        Image scaledIcon4 = iconLabel4.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH);
        jLabel4.setIcon(new ImageIcon(scaledIcon4));
        jLabel4.setHorizontalTextPosition(SwingConstants.RIGHT);
        jLabel4.setVerticalTextPosition(SwingConstants.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel2 = new raven.application.form.other.RoundedPanel();
        roundedPanel1 = new raven.application.form.other.RoundedPanel();
        lblTen = new javax.swing.JLabel();
        lblTongGhe = new javax.swing.JLabel();
        lblGioDi = new javax.swing.JLabel();
        lblGioDen = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblGheCon = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        lblNoPay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDiemBD = new javax.swing.JLabel();
        lblDiemden = new javax.swing.JLabel();
        lblQuangDuong = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 160));

        roundedPanel2.setBackground(new java.awt.Color(204, 204, 204));

        roundedPanel1.setPreferredSize(new java.awt.Dimension(425, 130));

        lblTen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTen.setText("Tên");

        lblTongGhe.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTongGhe.setText("Tống ghế");

        lblGioDi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGioDi.setText("Giờ đi");

        lblGioDen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGioDen.setText("Giờ đến");

        lblGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGia.setText("Giá");

        lblGheCon.setText("Số ghế còn");

        btnChon.setBackground(new java.awt.Color(24, 144, 255));
        btnChon.setText("Chọn Chuyến");

        lblNoPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNoPay.setText("KHÔNG CẦN THANH TOÁN TRƯỚC");

        jLabel3.setText("jLabel1");

        lblDiemBD.setText("Điểm bắt đầu");

        lblDiemden.setText("Điểm đến");

        lblQuangDuong.setText("Quảng đường");

        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel2.setText("jLabel1");

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGioDi)
                                    .addComponent(lblGioDen))
                                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDiemden))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDiemBD))))
                            .addComponent(lblTongGhe)
                            .addComponent(lblTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(lblQuangDuong)
                        .addGap(51, 51, 51)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGheCon)
                            .addComponent(btnChon)
                            .addComponent(lblGia)))
                    .addComponent(lblNoPay))
                .addGap(19, 19, 19))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblGheCon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChon))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTen)
                            .addComponent(lblGia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongGhe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGioDi)
                            .addComponent(lblDiemBD)
                            .addComponent(lblQuangDuong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGioDen)
                            .addComponent(lblDiemden)
                            .addComponent(jLabel2)
                            .addComponent(lblNoPay)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void updatePanelColors() {
        if (FlatLaf.isLafDark()) {
            roundedPanel2.setBackground(new Color(79, 92, 104, 255));
            roundedPanel1.setBackground(new Color(49, 62, 74, 255));
            btnChon.setBackground(new Color(79, 92, 104, 255));
            // Màu xám đậm cho dark mode
        } else {
            roundedPanel2.setBackground(new Color(230, 230, 230));
            roundedPanel1.setBackground(new Color(255, 255, 255));
            btnChon.setBackground(new Color(24,144,255));

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDiemBD;
    private javax.swing.JLabel lblDiemden;
    private javax.swing.JLabel lblGheCon;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblGioDen;
    private javax.swing.JLabel lblGioDi;
    private javax.swing.JLabel lblNoPay;
    private javax.swing.JLabel lblQuangDuong;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTongGhe;
    private raven.application.form.other.RoundedPanel roundedPanel1;
    private raven.application.form.other.RoundedPanel roundedPanel2;
    // End of variables declaration//GEN-END:variables
}
