/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form;

import com.formdev.flatlaf.FlatClientProperties;
import com.raven.datechooser.DateChooser;
import net.miginfocom.swing.MigLayout;
import raven.application.Application;
import raven.toast.Notifications;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
/**
 *
 * @author dinhk
 */
public class InfoForm extends javax.swing.JPanel {
    private DateChooser chDate = new DateChooser();
    
    /**
     * Creates new form InfoForm
     */
    public InfoForm() {
        initComponents();
        init();
    }
    private void init() {
        setLayout(new MigLayout("al center center"));

        lbTitle.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        
//        txtPass.putClientProperty(FlatClientProperties.STYLE, ""
//                + "showRevealButton:true;"
//                + "showCapsLock:true");
        cmdLogin.putClientProperty(FlatClientProperties.STYLE, ""
                + "borderWidth:0;"
                + "focusWidth:0");
        cmdQuaylai.putClientProperty(FlatClientProperties.STYLE, ""
                + "borderWidth:0;"
                + "focusWidth:0");
        txtHovaten.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Họ và tên");
        txtNgaySinh.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ngày sinh (DD/MM/YYYY)");
        chDate.setTextField(txtNgaySinh); 
        chDate.setDateFormat(new java.text.SimpleDateFormat("dd/MM/yyyy"));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin1 = new raven.application.form.PanelLogin();
        lbTitle = new javax.swing.JLabel();
        lbHovaten = new javax.swing.JLabel();
        txtHovaten = new javax.swing.JTextField();
        lbNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        cmdLogin = new javax.swing.JButton();
        cmdQuaylai = new javax.swing.JButton();

        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Thông tin cá nhân");
        panelLogin1.add(lbTitle);

        lbHovaten.setText("Họ và tên");
        panelLogin1.add(lbHovaten);
        panelLogin1.add(txtHovaten);

        lbNgaySinh.setText("Ngày sinh");
        panelLogin1.add(lbNgaySinh);
        panelLogin1.add(txtNgaySinh);

        cmdLogin.setText("Tiếp tục");
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });
        panelLogin1.add(cmdLogin);

        cmdQuaylai.setText("Quay Lại");
        cmdQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuaylaiActionPerformed(evt);
            }
        });
        panelLogin1.add(cmdQuaylai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        String ten = txtHovaten.getText().trim();
        String ngaysinh = txtNgaySinh.getText().trim();
        if (ten.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Vui lòng nhập họ và tên");
            return;
        }
        if (ngaysinh.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Vui lòng chọn ngày sinh");
            return;
        }
        if (!ngaysinh.matches("\\d{2}/\\d{2}/\\d{4}")) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Ngày sinh phải có định dạng DD/MM/YYYY");
            return;
        }
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);
            java.util.Date birthDate = sdf.parse(ngaysinh);
            String email = Application.getCurrentEmail();
            if (Application.getNguoiDungService().updateUserInfo(email, ten, birthDate)) {
                Application.login();
            } else {
                Notifications.getInstance().show(Notifications.Type.ERROR, "Không thể cập nhật thông tin");
            }
        } catch (ParseException e) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Ngày sinh không hợp lệ");
        } catch (SQLException e) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Lỗi kết nối cơ sở dữ liệu");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void cmdQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuaylaiActionPerformed
        // TODO add your handling code here:
        Application.register();
    }//GEN-LAST:event_cmdQuaylaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdQuaylai;
    private javax.swing.JLabel lbHovaten;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbTitle;
    private raven.application.form.PanelLogin panelLogin1;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
