/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form;

import com.formdev.flatlaf.FlatClientProperties;
import net.miginfocom.swing.MigLayout;
import raven.application.Application;
import raven.toast.Notifications;

import java.sql.SQLException;
/**
 *
 * @author dinhk
 */
public class OTPForm extends javax.swing.JPanel {

    /**
     * Creates new form OTPForm
     */
    public OTPForm() {
        initComponents();
        init();
    }
    private void init() {
        setLayout(new MigLayout("al center center"));

        lbTitle.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        

        cmdLogin.putClientProperty(FlatClientProperties.STYLE, ""
                + "borderWidth:0;"
                + "focusWidth:0");
        cmdQuaylai.putClientProperty(FlatClientProperties.STYLE, ""
                + "borderWidth:0;"
                + "focusWidth:0");
        txtMaxacthuc.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mã xác thực");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin1 = new raven.application.form.PanelLogin();
        lbTitle = new javax.swing.JLabel();
        lbMaxacthuc = new javax.swing.JLabel();
        txtMaxacthuc = new javax.swing.JTextField();
        cmdLogin = new javax.swing.JButton();
        cmdQuaylai = new javax.swing.JButton();

        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Nhập mã xác thực");
        panelLogin1.add(lbTitle);
        panelLogin1.add(lbMaxacthuc);
        panelLogin1.add(txtMaxacthuc);

        cmdLogin.setText("Tiếp tục");
        cmdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoginActionPerformed(evt);
            }
        });
        panelLogin1.add(cmdLogin);

        cmdQuaylai.setText("Quay lại");
        cmdQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdQuaylaiActionPerformed(evt);
            }
        });
        panelLogin1.add(cmdQuaylai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(panelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoginActionPerformed
        String otp = txtMaxacthuc.getText().trim();
        if (otp.isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Vui lòng nhập mã xác thực");
            return;
        }
        if (!otp.matches("\\d{6}")) {
            Notifications.getInstance().show(Notifications.Type.WARNING, "Mã xác thực phải có 6 chữ số");
            return;
        }
        try {
            String email = Application.getCurrentEmail();
            if (Application.getNguoiDungService().validateOTP(email, otp)) {
                if (Application.getNguoiDungService().needsUserInfo(email)) {
                    Application.showInfoForm();
                } else {
                    Application.login();
                }
            } else {
                Notifications.getInstance().show(Notifications.Type.WARNING, "Mã OTP không đúng hoặc đã hết hạn");
            }
        } catch (SQLException e) {
            Notifications.getInstance().show(Notifications.Type.ERROR, "Lỗi kết nối cơ sở dữ liệu");
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmdLoginActionPerformed

    private void cmdQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdQuaylaiActionPerformed
        // TODO add your handling code here:
        Application.backToPreviousForm();
    }//GEN-LAST:event_cmdQuaylaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLogin;
    private javax.swing.JButton cmdQuaylai;
    private javax.swing.JLabel lbMaxacthuc;
    private javax.swing.JLabel lbTitle;
    private raven.application.form.PanelLogin panelLogin1;
    private javax.swing.JTextField txtMaxacthuc;
    // End of variables declaration//GEN-END:variables
}
